<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library.Application\Library.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Scripts\" />
    <Folder Include="Data\Sql\Functions\" />
    <Folder Include="Data\Sql\Indexes\" />
    <Folder Include="Data\Sql\Views\" />
    <Folder Include="Data\Sql\StoredProcedures\" />
    <Folder Include="ExternalAPIs\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
