<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library.Application\Library.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Functions\" />
    <Folder Include="Database\Seed\" />
    <Folder Include="Database\Views\" />
    <Folder Include="Database\StoredProcedures\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="ExternalAPIs\" />
    <Folder Include="Persistence\UnitOfWork\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
